version: "3"

volumes:
  migrations: {}

services:
  mysql:
    image: mysql
    volumes:
      - migrations:/docker-entrypoint-initdb.d
    ports: 
      - "3306:3306"
    networks:
      - projeto
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "LALA"
      MYSQL_USER: "jessica"
      MYSQL_PASSWORD: "123456"

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    networks:
      - projeto

networks:
  projeto:


